# Generated by Django 2.1.3 on 2018-12-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredworks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
