# Generated by Django 2.1.3 on 2018-12-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_featuredworks_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gigs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(null=True)),
                ('Ticket', models.CharField(max_length=100)),
            ],
        ),
    ]
